---
abstract: 'pipe data to be fixed through an external process'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Fix-cmd
provides:
  Catmandu::Fix::cmd:
    file: lib/Catmandu/Fix/cmd.pm
    version: 0.0201
requires:
  Catmandu: 0.1
  IO::Pty::Easy: 0.09
  JSON::XS: 2.3
  namespace::clean: 0.24
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0201
